tv_paths:
    - E:\TV Library 00
    - H:\TV Library 03
    - I:\TV Library 04
    - J:\TV Library 05
    - K:\TV Library 06    
    - L:\TV Library 07
    - E:\Shows For Others
    - O:\Other Videos\Kids Stuff
    - G:\Kids TV Library 02

movie_paths:
    - M:\Movie Library 08
    - N:\Family Movies 09
    

