tv_paths:
    - H:\TV Library 03
    - I:\TV Library 04
    - J:\TV Library 05
    - L:\TV Library 07
    - N:\TV Library 09
    - N:\Shows For Others

movie_paths:
    - G:\Movie Library 02
    - K:\Movie Library 06
    - M:\Movie Library 08
    - O:\Family Movies 10
    - F:\Family Movies 01
