tv_paths:
  - /mnt/hdd/video/tv/kids
  - /mnt/hdd/video/tv/adults/jamy
  - /mnt/hdd/video/tv/adults/moppy
  - /mnt/hdd/video/tv/adults/jem
  - /mnt/hdd/mixed-shares/video/shows-for-others

movie_paths:
  - /mnt/hdd/video/movies/adults
  - /mnt/hdd/video/movies/kids
    

